### ISSUE TITLE
Prevent PR template insertion when the textarea is already populated

### ISSUE THREAD

**Issue by blakegearin** [RobQuistNL/chrome-github-jira#49] opened 2023-07-12 19:22 UTC
Steps to Reproduce

1. Go to a "Open a pull request" page
2. The extension will fill in the PR template
3. Type some information to prepare the PR for review
4. Reload the page
5. The information will show in the textarea for a brief moment
6. The extension will fill in the PR template, erasing previous work & effort 🙁

**Comment by RobQuistNL** [comment] 2023-07-13 11:11
oof, that sounds nasty! Good suggestion. Will see if I have time to implement this, probably shouldn't be too hard!

**Comment by RobQuistNL** [comment] 2024-08-23 08:28
Fixed in [v1.3.0](https://github.com/RobQuistNL/chrome-github-jira/releases/tag/v1.3.0)

**Closed** 2024-08-23 08:40 UTC

**Comment by rishabh-sagar-20** [comment] 2024-08-30 07:12
@RobQuistNL @blakegearin, this was the exact feature that has been working for me for the last 2 years. Now, the template doesn't even show up while creating a new PR :(

Is there any workaround?

**Comment by RobQuistNL** [comment] 2024-09-08 20:29
hmm, can you make me some reproduction steps @rishabh-sagar-20 ?

**Comment by blakegearin** [comment] 2024-09-10 01:35
@rishabh-sagar-20 `Ctrl` + `A` to select all of the description, then delete and refresh.

**Comment by RobQuistNL** [comment] 2024-09-10 10:05
You mean there's a "PR Template" in the .github folder in the repo and thats not being overwritten by this extension?

In my opinion thats by design - I don't want to overwrite any repo specific PR templates.

Or are you talking about something else? If its the first case, maybe we can add a button to "force" the Github-Jira PR template.

**Comment by rishabh-sagar-20** [comment] 2024-09-10 10:21
> You mean there's a "PR Template" in the .github folder in the repo and thats not being overwritten by this extension?
> 
> In my opinion thats by design - I don't want to overwrite any repo specific PR templates.
> 
> Or are you talking about something else? If its the first case, maybe we can add a button to "force" the Github-Jira PR template.

@RobQuistNL, It's not a repository-specific template; GitHub fills it in during the initial page load. The "force" button should work.

**Comment by RobQuistNL** [comment] 2024-09-10 14:34
Is this repository you talk about public, so I can check it out? Because if what you're saying is happening it means it shouldn't work at all for any  PR. :thinking:
