### ISSUE TITLE
Title frequently breaks, trying to insert link twice

### ISSUE THREAD

**Issue by mikeparker** [RobQuistNL/chrome-github-jira#27] opened 2019-03-05 11:53 UTC
Not sure exactly when this happens, when using back/forwards buttons or clicking links but the plugin frequently inserts the href twice, resulting in a mangled title with html inside.

![image](https://user-images.githubusercontent.com/1557887/53803645-38340900-3f3d-11e9-8c53-02c15bbb34a2.png)

**Comment by RobQuistNL** [comment] 2019-03-05 11:59
Oh wow, that doesn't look all too well! Its been a while since I've worked on this plugin, and there's some more issues open - I'll see what I can do later tonight. Thanks for the report, I will see if I can reproduce and solve it.

**Comment by RobQuistNL** [comment] 2019-04-02 22:09
Working on it right now :) Should be fixed in 1.2.0.

**Comment by RobQuistNL** [comment] 2019-04-02 22:41
Might have been fixed in 9f06e7a (will be version 1.2.0)
Let me know if this is still happening. If so, feel free to ping me!

**Closed by RobQuistNL** 2019-04-02 22:41 UTC
Labels: bug
